name: Fetch Webhook

on:
  repository_dispatch:
    types: [fetch_data]

jobs:
  handle_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Fetch Data Script
        run: |
          python scripts/fetch_data.py "${{ github.event.client_payload }}"
