name: Fetch Webhook

on:
  repository_dispatch:
    types: [fetch_data]

jobs:
  handle_webhook:
    runs-on: ubuntu-latest
    # 添加权限配置
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 更新到 v4 版本

      - name: Set up Python
        uses: actions/setup-python@v5  # 更新到 v5 版本
        with:
          python-version: '3.9'

      - name: Run Fetch Data Script
        run: |
          python scripts/fetch_data.py '${{ toJSON(github.event.client_payload) }}'

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git commit -m "Update data file" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF}
